# Generated by Django 4.0.5 on 2022-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='unknown', max_length=100)),
                ('author', models.CharField(default='unknown', max_length=100)),
                ('description', models.TextField(default='not available', max_length=200)),
                ('img_url', models.CharField(max_length=5000)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
